services:
  app:
    image: phonebook-front-dev
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    environment:
      REACT_APP_API_URL: http://localhost:8080/api
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules
  api:
    image: phonebook-back-dev
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      PORT: 80
      MONGODB_URL: mongodb://username-dev:password-dev@mongo:27017/the_database_test
  mongo:
    image: mongo
    expose:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root_test
      MONGO_INITDB_ROOT_PASSWORD: example_test
      MONGO_INITDB_DATABASE: the_database_test
    volumes:
      - ./backend/mongo/mongo-init-dev.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./backend/mongo/mongo_data_dev:/data/db
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 3000:80
    container_name: reverse-proxy-1
    depends_on:
      - app